sudo: false
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
before_install:
  - if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup default stable
  - rustc --version
install:
  - bundle install --path vendor/bundle
  - bundle exec rake helix:copy_dll build
after_success:
  - ruby ./bin/ci-publish $TRAVIS_TAG
matrix:
  include:
    - os: linux
      rvm: 2.3.8
      env:
        - GEM_PUBLISH=true
    - os: linux
      rvm: 2.3.8
      env:
        - NATIVE_BUNDLE=true
        - GEM_PUBLISH=true
    - os: osx
      osx_image: xcode9.2
      rvm: 2.3.8
      env:
        - NATIVE_BUNDLE=true
        - GEM_PUBLISH=true
    - os: osx
      osx_image: xcode10.1
      rvm: 2.3.8
      env:
        - NATIVE_BUNDLE=true
        - GEM_PUBLISH=true
